### ISSUE TITLE
Update to latest packages

### ISSUE THREAD

**Issue by MichalNemec** [nhost/nhost-dart#75]
Hello, could these packages be updated in dependencies? graphql_flutter has 5.1.0 with bindings fix and cannot use it.
```
  connectivity_plus: ^1.0.1 // there is version 2+
  flutter:
    sdk: flutter
  get: ^4.6.5
  graphql_flutter: ^5.0.0 //5.1.0 breaks
  nhost_flutter_auth: ^2.0.3
  nhost_flutter_graphql: ^2.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
```

thanks
